# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_Flag', models.CharField(max_length=32, verbose_name='删除标志')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=32, verbose_name='组名')),
                ('description', models.TextField(verbose_name='组描述')),
            ],
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('name', models.CharField(max_length=32, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限描述')),
            ],
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('permission_id', models.IntegerField(verbose_name='权限ID')),
                ('group_id', models.IntegerField(verbose_name='组ID')),
            ],
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
            ],
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('group_id', models.IntegerField(verbose_name='组ID')),
            ],
            bases=('users.basemodel',),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseModel')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('permission_id', models.IntegerField(verbose_name='权限ID')),
            ],
            bases=('users.basemodel',),
        ),
    ]
